# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/geilige/Documents/work/CLionProjects/wb-aes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/geilige/Documents/work/CLionProjects/wb-aes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/geilige/Documents/work/CLionProjects/wb-aes/CMakeFiles /Users/geilige/Documents/work/CLionProjects/wb-aes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/geilige/Documents/work/CLionProjects/wb-aes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testing

# Build rule for target.
testing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testing
.PHONY : testing

# fast build rule for target.
testing/fast:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/build
.PHONY : testing/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtesting

# Build rule for target.
gtesting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtesting
.PHONY : gtesting

# fast build rule for target.
gtesting/fast:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/build
.PHONY : gtesting/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

BGEAttack.o: BGEAttack.cpp.o

.PHONY : BGEAttack.o

# target to build an object file
BGEAttack.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/BGEAttack.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/BGEAttack.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/BGEAttack.cpp.o
.PHONY : BGEAttack.cpp.o

BGEAttack.i: BGEAttack.cpp.i

.PHONY : BGEAttack.i

# target to preprocess a source file
BGEAttack.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/BGEAttack.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/BGEAttack.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/BGEAttack.cpp.i
.PHONY : BGEAttack.cpp.i

BGEAttack.s: BGEAttack.cpp.s

.PHONY : BGEAttack.s

# target to generate assembly for a file
BGEAttack.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/BGEAttack.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/BGEAttack.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/BGEAttack.cpp.s
.PHONY : BGEAttack.cpp.s

EncTools.o: EncTools.cpp.o

.PHONY : EncTools.o

# target to build an object file
EncTools.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/EncTools.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/EncTools.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EncTools.cpp.o
.PHONY : EncTools.cpp.o

EncTools.i: EncTools.cpp.i

.PHONY : EncTools.i

# target to preprocess a source file
EncTools.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/EncTools.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/EncTools.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EncTools.cpp.i
.PHONY : EncTools.cpp.i

EncTools.s: EncTools.cpp.s

.PHONY : EncTools.s

# target to generate assembly for a file
EncTools.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/EncTools.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/EncTools.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EncTools.cpp.s
.PHONY : EncTools.cpp.s

GenericAES.o: GenericAES.cpp.o

.PHONY : GenericAES.o

# target to build an object file
GenericAES.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/GenericAES.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/GenericAES.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GenericAES.cpp.o
.PHONY : GenericAES.cpp.o

GenericAES.i: GenericAES.cpp.i

.PHONY : GenericAES.i

# target to preprocess a source file
GenericAES.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/GenericAES.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/GenericAES.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GenericAES.cpp.i
.PHONY : GenericAES.cpp.i

GenericAES.s: GenericAES.cpp.s

.PHONY : GenericAES.s

# target to generate assembly for a file
GenericAES.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/GenericAES.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/GenericAES.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GenericAES.cpp.s
.PHONY : GenericAES.cpp.s

InputObject.o: InputObject.cpp.o

.PHONY : InputObject.o

# target to build an object file
InputObject.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObject.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObject.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObject.cpp.o
.PHONY : InputObject.cpp.o

InputObject.i: InputObject.cpp.i

.PHONY : InputObject.i

# target to preprocess a source file
InputObject.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObject.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObject.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObject.cpp.i
.PHONY : InputObject.cpp.i

InputObject.s: InputObject.cpp.s

.PHONY : InputObject.s

# target to generate assembly for a file
InputObject.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObject.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObject.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObject.cpp.s
.PHONY : InputObject.cpp.s

InputObjectBuffer.o: InputObjectBuffer.cpp.o

.PHONY : InputObjectBuffer.o

# target to build an object file
InputObjectBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectBuffer.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectBuffer.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectBuffer.cpp.o
.PHONY : InputObjectBuffer.cpp.o

InputObjectBuffer.i: InputObjectBuffer.cpp.i

.PHONY : InputObjectBuffer.i

# target to preprocess a source file
InputObjectBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectBuffer.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectBuffer.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectBuffer.cpp.i
.PHONY : InputObjectBuffer.cpp.i

InputObjectBuffer.s: InputObjectBuffer.cpp.s

.PHONY : InputObjectBuffer.s

# target to generate assembly for a file
InputObjectBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectBuffer.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectBuffer.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectBuffer.cpp.s
.PHONY : InputObjectBuffer.cpp.s

InputObjectIOstream.o: InputObjectIOstream.cpp.o

.PHONY : InputObjectIOstream.o

# target to build an object file
InputObjectIOstream.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectIOstream.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectIOstream.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectIOstream.cpp.o
.PHONY : InputObjectIOstream.cpp.o

InputObjectIOstream.i: InputObjectIOstream.cpp.i

.PHONY : InputObjectIOstream.i

# target to preprocess a source file
InputObjectIOstream.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectIOstream.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectIOstream.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectIOstream.cpp.i
.PHONY : InputObjectIOstream.cpp.i

InputObjectIOstream.s: InputObjectIOstream.cpp.s

.PHONY : InputObjectIOstream.s

# target to generate assembly for a file
InputObjectIOstream.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectIOstream.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectIOstream.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectIOstream.cpp.s
.PHONY : InputObjectIOstream.cpp.s

InputObjectIstream.o: InputObjectIstream.cpp.o

.PHONY : InputObjectIstream.o

# target to build an object file
InputObjectIstream.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectIstream.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectIstream.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectIstream.cpp.o
.PHONY : InputObjectIstream.cpp.o

InputObjectIstream.i: InputObjectIstream.cpp.i

.PHONY : InputObjectIstream.i

# target to preprocess a source file
InputObjectIstream.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectIstream.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectIstream.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectIstream.cpp.i
.PHONY : InputObjectIstream.cpp.i

InputObjectIstream.s: InputObjectIstream.cpp.s

.PHONY : InputObjectIstream.s

# target to generate assembly for a file
InputObjectIstream.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectIstream.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectIstream.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectIstream.cpp.s
.PHONY : InputObjectIstream.cpp.s

InputObjectOstream.o: InputObjectOstream.cpp.o

.PHONY : InputObjectOstream.o

# target to build an object file
InputObjectOstream.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectOstream.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectOstream.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectOstream.cpp.o
.PHONY : InputObjectOstream.cpp.o

InputObjectOstream.i: InputObjectOstream.cpp.i

.PHONY : InputObjectOstream.i

# target to preprocess a source file
InputObjectOstream.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectOstream.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectOstream.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectOstream.cpp.i
.PHONY : InputObjectOstream.cpp.i

InputObjectOstream.s: InputObjectOstream.cpp.s

.PHONY : InputObjectOstream.s

# target to generate assembly for a file
InputObjectOstream.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/InputObjectOstream.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/InputObjectOstream.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/InputObjectOstream.cpp.s
.PHONY : InputObjectOstream.cpp.s

LinearAffineEq.o: LinearAffineEq.cpp.o

.PHONY : LinearAffineEq.o

# target to build an object file
LinearAffineEq.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/LinearAffineEq.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/LinearAffineEq.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/LinearAffineEq.cpp.o
.PHONY : LinearAffineEq.cpp.o

LinearAffineEq.i: LinearAffineEq.cpp.i

.PHONY : LinearAffineEq.i

# target to preprocess a source file
LinearAffineEq.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/LinearAffineEq.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/LinearAffineEq.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/LinearAffineEq.cpp.i
.PHONY : LinearAffineEq.cpp.i

LinearAffineEq.s: LinearAffineEq.cpp.s

.PHONY : LinearAffineEq.s

# target to generate assembly for a file
LinearAffineEq.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/LinearAffineEq.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/LinearAffineEq.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/LinearAffineEq.cpp.s
.PHONY : LinearAffineEq.cpp.s

LinearAffineEq_test.o: LinearAffineEq_test.cpp.o

.PHONY : LinearAffineEq_test.o

# target to build an object file
LinearAffineEq_test.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/LinearAffineEq_test.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/LinearAffineEq_test.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/LinearAffineEq_test.cpp.o
.PHONY : LinearAffineEq_test.cpp.o

LinearAffineEq_test.i: LinearAffineEq_test.cpp.i

.PHONY : LinearAffineEq_test.i

# target to preprocess a source file
LinearAffineEq_test.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/LinearAffineEq_test.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/LinearAffineEq_test.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/LinearAffineEq_test.cpp.i
.PHONY : LinearAffineEq_test.cpp.i

LinearAffineEq_test.s: LinearAffineEq_test.cpp.s

.PHONY : LinearAffineEq_test.s

# target to generate assembly for a file
LinearAffineEq_test.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/LinearAffineEq_test.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/LinearAffineEq_test.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/LinearAffineEq_test.cpp.s
.PHONY : LinearAffineEq_test.cpp.s

MixingBijections.o: MixingBijections.cpp.o

.PHONY : MixingBijections.o

# target to build an object file
MixingBijections.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/MixingBijections.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/MixingBijections.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MixingBijections.cpp.o
.PHONY : MixingBijections.cpp.o

MixingBijections.i: MixingBijections.cpp.i

.PHONY : MixingBijections.i

# target to preprocess a source file
MixingBijections.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/MixingBijections.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/MixingBijections.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MixingBijections.cpp.i
.PHONY : MixingBijections.cpp.i

MixingBijections.s: MixingBijections.cpp.s

.PHONY : MixingBijections.s

# target to generate assembly for a file
MixingBijections.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/MixingBijections.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/MixingBijections.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MixingBijections.cpp.s
.PHONY : MixingBijections.cpp.s

NTLUtils.o: NTLUtils.cpp.o

.PHONY : NTLUtils.o

# target to build an object file
NTLUtils.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/NTLUtils.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/NTLUtils.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NTLUtils.cpp.o
.PHONY : NTLUtils.cpp.o

NTLUtils.i: NTLUtils.cpp.i

.PHONY : NTLUtils.i

# target to preprocess a source file
NTLUtils.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/NTLUtils.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/NTLUtils.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NTLUtils.cpp.i
.PHONY : NTLUtils.cpp.i

NTLUtils.s: NTLUtils.cpp.s

.PHONY : NTLUtils.s

# target to generate assembly for a file
NTLUtils.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/NTLUtils.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/NTLUtils.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NTLUtils.cpp.s
.PHONY : NTLUtils.cpp.s

RingBuffer.o: RingBuffer.cpp.o

.PHONY : RingBuffer.o

# target to build an object file
RingBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/RingBuffer.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/RingBuffer.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/RingBuffer.cpp.o
.PHONY : RingBuffer.cpp.o

RingBuffer.i: RingBuffer.cpp.i

.PHONY : RingBuffer.i

# target to preprocess a source file
RingBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/RingBuffer.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/RingBuffer.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/RingBuffer.cpp.i
.PHONY : RingBuffer.cpp.i

RingBuffer.s: RingBuffer.cpp.s

.PHONY : RingBuffer.s

# target to generate assembly for a file
RingBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/RingBuffer.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/RingBuffer.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/RingBuffer.cpp.s
.PHONY : RingBuffer.cpp.s

WBAES.o: WBAES.cpp.o

.PHONY : WBAES.o

# target to build an object file
WBAES.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/WBAES.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/WBAES.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WBAES.cpp.o
.PHONY : WBAES.cpp.o

WBAES.i: WBAES.cpp.i

.PHONY : WBAES.i

# target to preprocess a source file
WBAES.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/WBAES.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/WBAES.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WBAES.cpp.i
.PHONY : WBAES.cpp.i

WBAES.s: WBAES.cpp.s

.PHONY : WBAES.s

# target to generate assembly for a file
WBAES.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/WBAES.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/WBAES.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WBAES.cpp.s
.PHONY : WBAES.cpp.s

WBAESGenerator.o: WBAESGenerator.cpp.o

.PHONY : WBAESGenerator.o

# target to build an object file
WBAESGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/WBAESGenerator.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/WBAESGenerator.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WBAESGenerator.cpp.o
.PHONY : WBAESGenerator.cpp.o

WBAESGenerator.i: WBAESGenerator.cpp.i

.PHONY : WBAESGenerator.i

# target to preprocess a source file
WBAESGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/WBAESGenerator.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/WBAESGenerator.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WBAESGenerator.cpp.i
.PHONY : WBAESGenerator.cpp.i

WBAESGenerator.s: WBAESGenerator.cpp.s

.PHONY : WBAESGenerator.s

# target to generate assembly for a file
WBAESGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/WBAESGenerator.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/WBAESGenerator.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/WBAESGenerator.cpp.s
.PHONY : WBAESGenerator.cpp.s

base.o: base.cpp.o

.PHONY : base.o

# target to build an object file
base.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/base.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/base.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/base.cpp.o
.PHONY : base.cpp.o

base.i: base.cpp.i

.PHONY : base.i

# target to preprocess a source file
base.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/base.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/base.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/base.cpp.i
.PHONY : base.cpp.i

base.s: base.cpp.s

.PHONY : base.s

# target to generate assembly for a file
base.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/base.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/base.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/base.cpp.s
.PHONY : base.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

md5.o: md5.c.o

.PHONY : md5.o

# target to build an object file
md5.c.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/md5.c.o
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/md5.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/md5.c.o
.PHONY : md5.c.o

md5.i: md5.c.i

.PHONY : md5.i

# target to preprocess a source file
md5.c.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/md5.c.i
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/md5.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/md5.c.i
.PHONY : md5.c.i

md5.s: md5.c.s

.PHONY : md5.s

# target to generate assembly for a file
md5.c.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/md5.c.s
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/md5.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/md5.c.s
.PHONY : md5.c.s

testing.o: testing.cpp.o

.PHONY : testing.o

# target to build an object file
testing.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/testing.cpp.o
.PHONY : testing.cpp.o

testing.i: testing.cpp.i

.PHONY : testing.i

# target to preprocess a source file
testing.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/testing.cpp.i
.PHONY : testing.cpp.i

testing.s: testing.cpp.s

.PHONY : testing.s

# target to generate assembly for a file
testing.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/testing.cpp.s
.PHONY : testing.cpp.s

tests/Commons.o: tests/Commons.cpp.o

.PHONY : tests/Commons.o

# target to build an object file
tests/Commons.cpp.o:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/Commons.cpp.o
.PHONY : tests/Commons.cpp.o

tests/Commons.i: tests/Commons.cpp.i

.PHONY : tests/Commons.i

# target to preprocess a source file
tests/Commons.cpp.i:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/Commons.cpp.i
.PHONY : tests/Commons.cpp.i

tests/Commons.s: tests/Commons.cpp.s

.PHONY : tests/Commons.s

# target to generate assembly for a file
tests/Commons.cpp.s:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/Commons.cpp.s
.PHONY : tests/Commons.cpp.s

tests/EncToolsTest.o: tests/EncToolsTest.cpp.o

.PHONY : tests/EncToolsTest.o

# target to build an object file
tests/EncToolsTest.cpp.o:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/EncToolsTest.cpp.o
.PHONY : tests/EncToolsTest.cpp.o

tests/EncToolsTest.i: tests/EncToolsTest.cpp.i

.PHONY : tests/EncToolsTest.i

# target to preprocess a source file
tests/EncToolsTest.cpp.i:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/EncToolsTest.cpp.i
.PHONY : tests/EncToolsTest.cpp.i

tests/EncToolsTest.s: tests/EncToolsTest.cpp.s

.PHONY : tests/EncToolsTest.s

# target to generate assembly for a file
tests/EncToolsTest.cpp.s:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/EncToolsTest.cpp.s
.PHONY : tests/EncToolsTest.cpp.s

tests/RingBufferTest.o: tests/RingBufferTest.cpp.o

.PHONY : tests/RingBufferTest.o

# target to build an object file
tests/RingBufferTest.cpp.o:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/RingBufferTest.cpp.o
.PHONY : tests/RingBufferTest.cpp.o

tests/RingBufferTest.i: tests/RingBufferTest.cpp.i

.PHONY : tests/RingBufferTest.i

# target to preprocess a source file
tests/RingBufferTest.cpp.i:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/RingBufferTest.cpp.i
.PHONY : tests/RingBufferTest.cpp.i

tests/RingBufferTest.s: tests/RingBufferTest.cpp.s

.PHONY : tests/RingBufferTest.s

# target to generate assembly for a file
tests/RingBufferTest.cpp.s:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/RingBufferTest.cpp.s
.PHONY : tests/RingBufferTest.cpp.s

tests/WBAes.o: tests/WBAes.cpp.o

.PHONY : tests/WBAes.o

# target to build an object file
tests/WBAes.cpp.o:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/WBAes.cpp.o
.PHONY : tests/WBAes.cpp.o

tests/WBAes.i: tests/WBAes.cpp.i

.PHONY : tests/WBAes.i

# target to preprocess a source file
tests/WBAes.cpp.i:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/WBAes.cpp.i
.PHONY : tests/WBAes.cpp.i

tests/WBAes.s: tests/WBAes.cpp.s

.PHONY : tests/WBAes.s

# target to generate assembly for a file
tests/WBAes.cpp.s:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/WBAes.cpp.s
.PHONY : tests/WBAes.cpp.s

tests/tester.o: tests/tester.cpp.o

.PHONY : tests/tester.o

# target to build an object file
tests/tester.cpp.o:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/tester.cpp.o
.PHONY : tests/tester.cpp.o

tests/tester.i: tests/tester.cpp.i

.PHONY : tests/tester.i

# target to preprocess a source file
tests/tester.cpp.i:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/tester.cpp.i
.PHONY : tests/tester.cpp.i

tests/tester.s: tests/tester.cpp.s

.PHONY : tests/tester.s

# target to generate assembly for a file
tests/tester.cpp.s:
	$(MAKE) -f CMakeFiles/gtesting.dir/build.make CMakeFiles/gtesting.dir/tests/tester.cpp.s
.PHONY : tests/tester.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... testing"
	@echo "... gtest"
	@echo "... gtesting"
	@echo "... main"
	@echo "... BGEAttack.o"
	@echo "... BGEAttack.i"
	@echo "... BGEAttack.s"
	@echo "... EncTools.o"
	@echo "... EncTools.i"
	@echo "... EncTools.s"
	@echo "... GenericAES.o"
	@echo "... GenericAES.i"
	@echo "... GenericAES.s"
	@echo "... InputObject.o"
	@echo "... InputObject.i"
	@echo "... InputObject.s"
	@echo "... InputObjectBuffer.o"
	@echo "... InputObjectBuffer.i"
	@echo "... InputObjectBuffer.s"
	@echo "... InputObjectIOstream.o"
	@echo "... InputObjectIOstream.i"
	@echo "... InputObjectIOstream.s"
	@echo "... InputObjectIstream.o"
	@echo "... InputObjectIstream.i"
	@echo "... InputObjectIstream.s"
	@echo "... InputObjectOstream.o"
	@echo "... InputObjectOstream.i"
	@echo "... InputObjectOstream.s"
	@echo "... LinearAffineEq.o"
	@echo "... LinearAffineEq.i"
	@echo "... LinearAffineEq.s"
	@echo "... LinearAffineEq_test.o"
	@echo "... LinearAffineEq_test.i"
	@echo "... LinearAffineEq_test.s"
	@echo "... MixingBijections.o"
	@echo "... MixingBijections.i"
	@echo "... MixingBijections.s"
	@echo "... NTLUtils.o"
	@echo "... NTLUtils.i"
	@echo "... NTLUtils.s"
	@echo "... RingBuffer.o"
	@echo "... RingBuffer.i"
	@echo "... RingBuffer.s"
	@echo "... WBAES.o"
	@echo "... WBAES.i"
	@echo "... WBAES.s"
	@echo "... WBAESGenerator.o"
	@echo "... WBAESGenerator.i"
	@echo "... WBAESGenerator.s"
	@echo "... base.o"
	@echo "... base.i"
	@echo "... base.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... md5.o"
	@echo "... md5.i"
	@echo "... md5.s"
	@echo "... testing.o"
	@echo "... testing.i"
	@echo "... testing.s"
	@echo "... tests/Commons.o"
	@echo "... tests/Commons.i"
	@echo "... tests/Commons.s"
	@echo "... tests/EncToolsTest.o"
	@echo "... tests/EncToolsTest.i"
	@echo "... tests/EncToolsTest.s"
	@echo "... tests/RingBufferTest.o"
	@echo "... tests/RingBufferTest.i"
	@echo "... tests/RingBufferTest.s"
	@echo "... tests/WBAes.o"
	@echo "... tests/WBAes.i"
	@echo "... tests/WBAes.s"
	@echo "... tests/tester.o"
	@echo "... tests/tester.i"
	@echo "... tests/tester.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

